name: Testing the GitHub Pages publication

on: push

jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      # Standard usage
      - uses: helaili/jekyll-action@2.0.0
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}